[package]
name = "rust-wasm-hotreload"
version = "0.1.0"
authors = ["Shady Khalifa <shekohex@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
wasmtime = { version = "0.19", default-features = false }
notify = "4.0"
atomic_refcell = "0.1"
